export type radius = '1' | '2' | '3' | '4' | 'round' | 'none'
export type width = 'xs' | 'sm' | 'md' | 'lg' | 'auto' | 'none'
export type theme =
  | 'primary'
  | 'secondary'
  | 'info'
  | 'success'
  | 'warning'
  | 'danger'
  | 'disabled'
export type justifyContent =
  | 'space-between'
  | 'space-around'
  | 'space-evenly'
  | 'center'
  | 'start'
  | 'end'
  | 'unset'
  | 'initial'
export type fadeTimes =
  | '0.1s'
  | '0.2s'
  | '0.3s'
  | '0.5s'
  | '0.7s'
  | '0.8s'
  | '1s'
  | '1.2s'
  | '1.4s'
  | '1.6s'
  | '1.8s'
  | '2s'
